import "@/styles/global.css";
import { ReactNode } from "react";
import GlassPane from "@/components/GlassPane";
import Sidebar from "@/components/Sidebar";

type IProps = {
  children: ReactNode;
};

export default function DashboardRootLayout({ children }: IProps) {
  return (
    <html lang="en">
      <head>
        <title>Shopping List App</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
      </head>
      <body className="h-screen w-screen rainbow-mesh">
        <GlassPane className="w-full h-full flex items-center">
          <Sidebar />
          {children}{" "}
        </GlassPane>
        <div id="modal"></div>
      </body>
    </html>
  );
}
